"use client";

import { useMemo, useState } from "react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  ArrowRight,
  Heart,
  Eye,
  Clock,
  Palette,
  MapPin,
  Zap,
  TrendingUp,
  Users,
  Sparkles,
} from "lucide-react";
import Link from "next/link";
import { cn } from "@/utils/cn";
import {
  communityGalleryCategories,
  communityGalleryItems,
} from "@/lib/gallery/community-gallery";

const stats = [
  { label: "Total Designs", value: "12,847", icon: Sparkles },
  { label: "Active Artists", value: "3,291", icon: Users },
  { label: "Style Categories", value: "50+", icon: Palette },
  { label: "Trending Now", value: "Neo-Traditional", icon: TrendingUp },
];

export function Gallery() {
  const [activeCategory, setActiveCategory] = useState("All");
  const [likedItems, setLikedItems] = useState<Set<number>>(new Set());

  const filteredItems = useMemo(() => {
    if (activeCategory === "All") {
      return communityGalleryItems;
    }

    return communityGalleryItems.filter((item) => item.style === activeCategory);
  }, [activeCategory]);

  const toggleLike = (id: number) => {
    setLikedItems((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  };

  return (
    <section id="gallery" className="py-24">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="mb-8 flex flex-col sm:flex-row sm:items-end sm:justify-between">
          <div>
            <h2 className="text-3xl font-bold tracking-tight text-white sm:text-4xl">
              Community
              <span className="bg-gradient-to-r from-brand-400 to-pink-400 bg-clip-text text-transparent">
                {" "}
                Gallery
              </span>
            </h2>
            <p className="mt-4 text-lg text-white/60">
              Tattoo flash sheets generated by the community, ready to remix or try on
            </p>
          </div>
          <Link href="/gallery" className="mt-4 sm:mt-0">
            <Button variant="outline">
              Explore All
              <ArrowRight className="ml-2 h-4 w-4" />
            </Button>
          </Link>
        </div>

        <div className="mb-10 grid grid-cols-2 gap-4 md:grid-cols-4">
          {stats.map((stat) => (
            <div
              key={stat.label}
              className="flex items-center gap-3 rounded-xl border border-white/10 bg-white/5 p-4"
            >
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-brand-500/20">
                <stat.icon className="h-5 w-5 text-brand-400" />
              </div>
              <div>
                <p className="text-lg font-bold text-white">{stat.value}</p>
                <p className="text-xs text-white/50">{stat.label}</p>
              </div>
            </div>
          ))}
        </div>

        <div className="mb-8 flex gap-2 overflow-x-auto pb-4 scrollbar-hide">
          {communityGalleryCategories.map((category) => (
            <button
              key={category}
              onClick={() => setActiveCategory(category)}
              className={cn(
                "whitespace-nowrap rounded-full px-4 py-2 text-sm font-medium transition-all",
                activeCategory === category
                  ? "bg-brand-500 text-white"
                  : "bg-white/5 text-white/60 hover:bg-white/10 hover:text-white"
              )}
            >
              {category}
            </button>
          ))}
        </div>

        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {filteredItems.map((item) => (
            <Card
              key={item.id}
              className="group relative cursor-pointer overflow-hidden border-white/10 bg-white/5"
            >
              <div className="relative aspect-[4/5] overflow-hidden">
                <div className="absolute inset-0 bg-[radial-gradient(circle_at_top,#42362c,transparent_56%),linear-gradient(160deg,#f6efdf_0%,#eadcc3_52%,#f8f3e8_100%)] opacity-95 transition-transform duration-500 group-hover:scale-[1.02]" />
                <div className="absolute inset-3 rounded-[28px] border border-black/10 bg-[linear-gradient(135deg,rgba(255,255,255,0.68),rgba(255,255,255,0.12))] shadow-[inset_0_1px_0_rgba(255,255,255,0.45),0_18px_30px_rgba(0,0,0,0.12)]" />
                <div className="absolute inset-0 flex items-center justify-center p-8 sm:p-10">
                  <img
                    src={item.image}
                    alt={`${item.style} tattoo - ${item.prompt}`}
                    className="h-full w-full object-contain drop-shadow-[0_16px_26px_rgba(0,0,0,0.18)] transition-transform duration-500 group-hover:scale-105"
                  />
                </div>

                <div className="absolute left-3 right-3 top-3 flex items-start justify-between">
                  <div className="flex gap-2">
                    <span className="rounded-md bg-black/60 px-2 py-1 text-xs font-medium text-white/90 backdrop-blur-sm">
                      {item.style}
                    </span>
                    {item.isHot && (
                      <Badge className="border-0 bg-red-500/80 text-xs text-white">
                        <Zap className="mr-1 h-3 w-3" />
                        Hot
                      </Badge>
                    )}
                    {item.isNew && (
                      <Badge className="border-0 bg-brand-500/80 text-xs text-white">
                        New
                      </Badge>
                    )}
                  </div>
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      toggleLike(item.id);
                    }}
                    className="rounded-full bg-black/40 p-2 backdrop-blur-sm transition-colors hover:bg-black/60"
                  >
                    <Heart
                      className={cn(
                        "h-4 w-4 transition-colors",
                        likedItems.has(item.id)
                          ? "fill-red-500 text-red-500"
                          : "text-white/80"
                      )}
                    />
                  </button>
                </div>

                <div className="absolute bottom-0 left-0 right-0 p-4">
                  <p className="line-clamp-2 text-sm font-medium text-black/80">
                    {item.prompt}
                  </p>
                  <div className="mt-2 flex items-center gap-3 text-black/55">
                    <span className="flex items-center gap-1 text-xs">
                      <MapPin className="h-3 w-3" />
                      {item.placement}
                    </span>
                    <span className="flex items-center gap-1 text-xs">
                      <Palette className="h-3 w-3" />
                      {item.colorMode}
                    </span>
                  </div>
                </div>
              </div>

              <div className="border-t border-white/5 p-3">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <div className="flex h-7 w-7 items-center justify-center rounded-full bg-gradient-to-br from-brand-500 to-brand-700 text-xs font-bold text-white">
                      {item.avatar}
                    </div>
                    <span className="text-xs text-white/70">{item.artist}</span>
                  </div>
                  <div className="flex items-center gap-3 text-white/40">
                    <span className="flex items-center gap-1 text-xs">
                      <Heart className="h-3 w-3" />
                      {item.likes + (likedItems.has(item.id) ? 1 : 0)}
                    </span>
                    <span className="flex items-center gap-1 text-xs">
                      <Eye className="h-3 w-3" />
                      {item.views}
                    </span>
                    <span className="flex items-center gap-1 text-xs">
                      <Clock className="h-3 w-3" />
                      {item.generationTime}
                    </span>
                  </div>
                </div>
              </div>

              <div className="pointer-events-none absolute inset-0 flex items-center justify-center bg-black/45 opacity-0 transition-opacity duration-300 group-hover:opacity-100">
                <Button size="sm" className="pointer-events-auto gap-2">
                  <Eye className="h-4 w-4" />
                  View Design
                </Button>
              </div>
            </Card>
          ))}
        </div>

        <div className="mt-10 text-center">
          <Link href="/gallery">
            <Button variant="outline" size="lg" className="gap-2">
              <Sparkles className="h-4 w-4" />
              Load More Designs
            </Button>
          </Link>
        </div>
      </div>
    </section>
  );
}
